#include "BTSOverlay.h"

typedef struct {
	A_u_long	index;
	A_char		str[256];
} TableString;

TableString		g_strs[StrID_NUMTYPES] = {
	StrID_NONE,					"",
	StrID_Name,					"BTS Overlay",
	StrID_Description,			"Draws behind-the-scenes production overlays (nulls + motion paths) onto the composite.\rApply to an adjustment layer at the top of the comp.",
	StrID_View_Param_Name,			"View",
	StrID_View_Choices,				"Final|Debug Values",
	StrID_ShowOverlays_Param_Name,	"Show Overlays",
	StrID_OverlaysOnly_Param_Name,	"Overlays Only",
	StrID_Opacity_Param_Name,		"Overlay Opacity",
	StrID_Timing_Topic,				"Time Range",
	StrID_Visibility_Param_Name,	"Range",
	StrID_Visibility_Choices,		"Whole Composition|Window Around CTI",
	StrID_WinStart_Param_Name,		"Seconds Before",
	StrID_WinLen_Param_Name,		"Seconds After",
	StrID_Markers_Topic,			"Layer Markers",
	StrID_ShowMarkers_Param_Name,	"Show Markers",
	StrID_MarkerStyle_Param_Name,	"Marker Style",
	StrID_MarkerStyle_Choices,		"Anchor (AE)|Crosshair|Dot",
	StrID_MarkerColor_Param_Name,	"Marker Color",
	StrID_MarkerSize_Param_Name,	"Marker Size",
	StrID_ShowAxes_Param_Name,		"3D Axis Handles",
	StrID_AxisLen_Param_Name,		"Axis Length",
	StrID_AxisWidth_Param_Name,		"Axis Width",
	StrID_AxisHead_Param_Name,		"Arrowhead",
	StrID_AxisHead_Choices,			"Barbs|Triangle (cone)",
	StrID_Paths_Topic,				"Motion Paths",
	StrID_ShowPaths_Param_Name,		"Show Paths",
	StrID_PathColor_Param_Name,		"Path Color",
	StrID_PathThick_Param_Name,		"Path Thickness",
	StrID_ShowKfDots_Param_Name,	"Keyframe Dots",
	StrID_ShowTangents_Param_Name,	"Tangent Handles",
	StrID_ShowFrameDots_Param_Name,	"Frame Dots (velocity)",
	StrID_Boxes_Topic,				"Bounding Boxes",
	StrID_ShowBoxes_Param_Name,		"Show Bounding Boxes",
	StrID_BoxColor_Param_Name,		"Box Color",
	StrID_BoxThick_Param_Name,		"Box Thickness",
	StrID_ShowHandles_Param_Name,	"Corner Handles",
	StrID_HandleColor_Param_Name,	"Handle Color",
	StrID_HandleSize_Param_Name,	"Handle Size",
	StrID_Types_Topic,				"Layer Types",
	StrID_ColorSource_Param_Name,	"Gizmo Colors",
	StrID_ColorSource_Choices,		"Per Gizmo|By Layer Type|By Label",
	StrID_Cameras_Param_Name,		"Cameras",
	StrID_CamerasColor_Param_Name,	"Camera Color",
	StrID_Lights_Param_Name,		"Lights",
	StrID_LightsColor_Param_Name,	"Light Color",
	StrID_Nulls_Param_Name,			"Nulls",
	StrID_NullsColor_Param_Name,	"Null Color",
	StrID_Adjust_Param_Name,		"Adjustment Layers",
	StrID_AdjustColor_Param_Name,	"Adjustment Color",
	StrID_Text_Param_Name,			"Text Layers",
	StrID_TextColor_Param_Name,		"Text Color",
	StrID_Shapes_Param_Name,		"Shape Layers",
	StrID_ShapesColor_Param_Name,	"Shape Color",
	StrID_Precomps_Param_Name,		"Precomps",
	StrID_PrecompsColor_Param_Name,	"Precomp Color",
	StrID_Solids_Param_Name,		"Solids",
	StrID_SolidsColor_Param_Name,	"Solid Color",
	StrID_Footage_Param_Name,		"Footage / Other",
	StrID_FootageColor_Param_Name,	"Footage Color",
	StrID_Models_Param_Name,		"3D Models",
	StrID_ModelsColor_Param_Name,	"3D Model Color",
	StrID_Prims_Param_Name,		"3D Primitives",
	StrID_PrimsColor_Param_Name,	"3D Primitive Color",
	StrID_Guides_Param_Name,		"Include Guide Layers",
	StrID_Locked_Param_Name,		"Include Locked Layers",
	StrID_Dump_Param_Name,			"Dump Diagnostics",
};

char	*GetStringPtr(int strNum)
{
	return g_strs[strNum].str;
}
